name: NodeJS with Webpack
# Este workflow compila el proyecto usando Webpack en
# varias versiones de Node.js cuando se realizan cambios

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # El job se ejecuta en la última versión estable de Ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Se prueba la build en distintas versiones de Node
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        # Instalación de dependencias y compilación mediante Webpack
        npm install
        npx webpack
